title: "Brandon Sena - Personal Website & Resume"
description: "Brandon Sena - Personal Website & Resume powered by Jekyll"
url: "https://brandon97sena.github.io"
baseurl: ""  # Leave as "" for a user site or set to your repo name if it's a project page

theme: jekyll-theme-hacker

# Author Information
author:
  name: "Brandon Sena"
  email: "brandon97sena@example.com"
  
# Social links
social_links:
  github: "https://github.com/brandon97sena"
  linkedin: "https://www.linkedin.com/in/brandon-sena/"
